### ISSUE TITLE
Crashes on 1.18.2

### ISSUE THREAD

**Issue by sssssssthedev** [TheGaming999/PrisonRanksX#5]
![uyn6hLXC](https://user-images.githubusercontent.com/69808781/166728759-c41c8310-c2ef-450f-8f02-7709df577acf.png)
This is what i get when trying to run this on 1.18.2.
Stacktrace:
![lAqtHnTD](https://user-images.githubusercontent.com/69808781/166728838-f3114c51-c60e-4891-9afe-71a0349eb429.png)
Line in question is https://github.com/TheGaming999/PrisonRanksX/blob/master/src/me/prisonranksx/utils/EventPriorityManager.java#L459

**Comment by sssssssthedev** [comment]
Also, happens on both java 17 and 18.

**Comment by Sandwichas** [comment]
Seems to be working fine for me:
![Screenshot_4](https://user-images.githubusercontent.com/14120627/166805353-76cf9c7a-dfeb-4cc8-84ee-0ae7761781c2.png)
I used Java 17. Are you sure that you are using the latest version of 1.18.2?

**Comment by Sandwichas** [comment]
Anyway, here is a version without EventPriorityManager. Test it and tell me if it works or not.
[PrisonRanksX-2.8.5dev_03.zip](https://github.com/TheGaming999/PrisonRanksX/files/8626746/PrisonRanksX-2.8.5dev_03.zip)

**Comment by sssssssthedev** [comment]
I'm at school rn, I do have purpur so I am gonna test your version with purpur and then the other version withouth purpur.

**Comment by sssssssthedev** [comment]
I don't know exactly what are you running, but latest spigot 1.18.2 gives me this
![EVyCBnTh](https://user-images.githubusercontent.com/69808781/166930206-ea2b3997-543e-4153-b5e7-e3c0cca5a4e4.png)
Your dev03 version does work on purpur (and probably would on spigot) withouth any problems. Weird

**Comment by sssssssthedev** [comment]
Also that was just testing the dev version from discord on normal spigot (cause it was fine on your end from the ss)

**Comment by Sandwichas** [comment]
> I don't know exactly what are you running, but latest spigot 1.18.2 gives me this ![EVyCBnTh](https://user-images.githubusercontent.com/69808781/166930206-ea2b3997-543e-4153-b5e7-e3c0cca5a4e4.png) Your dev03 version does work on purpur (and probably would on spigot) withouth any problems. Weird

This was indeed an issue and it has been fixed. It must be a problem from your end. It even works for me with the latest version of Purpur:
![Screenshot_5](https://user-images.githubusercontent.com/14120627/166977876-f2985966-0d47-4502-99f8-ceb2bcbfdd1c.png)

**Comment by Sandwichas** [comment]
Also, I used the latest update of java 18 if that makes any difference

**Comment by sssssssthedev** [comment]
Weird, atleast it works now with the dev03 version, so i'm closing the issue.
